# CS5720: Neural Networks and Deep Learning (Spring 2025)
## ICP 2 - Problem 2
**Student Name:** Nidhin Ninan

**School:** University of Central Missouri

**Video Link:** https://drive.google.com/file/d/1WjSHpy91Yn-WzhPcIszfnTF46LuW9O3q/view?usp=sharing

Importing Libraries

In [5]:
import numpy as np

Creating a 1-D arr with 20 elements with float numbers between 1 and 20.
- np.round.uniform with generate numbers in any given specific range
- Using np.round() to limit the number of decimal places to 2

In [6]:
#create random arra of 20 elements between 0 and 20
x = np.round(np.random.uniform(low=1.0 , high=20.0 , size=20),2) #round off decimal laces to 2
print(f"Original Array : {x}")

Original Array : [ 9.67 11.49 13.62  1.01 16.44 10.64  2.19  9.98  8.15 17.05 13.2  19.65
  7.68 14.94 18.33  1.14  4.34  3.29  8.47 18.05]


Change the 20 elem 1-D array dimension into 2-D using np.reshape

In [7]:
x_reshape = x.reshape(4,5) # change form 20 elemt 1-D arr to 4 row and 5 col 2-D arr
print(f"Reshaped Array (4x5) : {x_reshape}")

Reshaped Array (4x5) : [[ 9.67 11.49 13.62  1.01 16.44]
 [10.64  2.19  9.98  8.15 17.05]
 [13.2  19.65  7.68 14.94 18.33]
 [ 1.14  4.34  3.29  8.47 18.05]]


Substitute the max element in each row with 0 using the following logic
- Using np.argmax() to find the index of the max element in each row
- Then traverse through ach row of the arr using np.arange and and the max_index found earlier

In [8]:
max_index = np.argmax(x_reshape, axis=1) #find the COL INDEX of max element in each row
#substitute each max elemt in each row with 0
x_reshape[np.arange(x_reshape.shape[0]),max_index] = 0 #arange generates temp arr of 0 to number of rows of arr-1
# cycle through [[0,1,2,3], max elemt of row index]

print(f"Max Element Substituted Array (4x5) : {x_reshape}")

Max Element Substituted Array (4x5) : [[ 9.67 11.49 13.62  1.01  0.  ]
 [10.64  2.19  9.98  8.15  0.  ]
 [13.2   0.    7.68 14.94 18.33]
 [ 1.14  4.34  3.29  8.47  0.  ]]


**VIDEO LINK** : https://drive.google.com/file/d/1WjSHpy91Yn-WzhPcIszfnTF46LuW9O3q/view?usp=sharing